spring:
  application:
    name: delivery

  # DB 연결 — 3-3의 docker run 값과 똑같이
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: delivery
    password: delivery1234!!

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

admin:
  token: "AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC"